# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

# We do not work on the "trusty" container yet
dist: precise

matrix:
  include:
  - os: linux
    env:
      - PYTHON_VER='3.5'

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

# Build out environment
  - conda create -n sss python=3.5 cmake psi4 numpy lawrap cmake scipy mkl-include gcc-5-mp -c intel -c psi4/label/dev -c psi4
  - source activate sss
  - conda list

# Install various required modules
  - pip install --upgrade pip setuptools
  - pip install pytest pytest-cov
  - pip install codecov

# Build the C++
  - python setup.py cmake

# Install the plugin locally
  - pip install -e .

before_script:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - python -c 'import numpy; print(numpy.version.version)'

script:
  - py.test -v --cov=./

notifications:
    email: false

after_success:
  - codecov
